### ISSUE TITLE
Set Locale / Language

### ISSUE THREAD

**Issue by air101** [icambron/timestack#2]
Good Evening,

thank you for that nice project! I just have one question, how do I set the locale time zone information for timestack / moment? I dont want the AM/PM and english calendar thinggy in my project.

Thank you in advance!
- air

**Comment by icambron** [comment]
If you're using the version of Moment that supports different locales (see the download section [here](http://momentjs.com/)), you can just set it globally for all of Moment:

``` js
moment.locale('en-uk'); //or whatever
```

That should change how Timestack displays the time.

**Comment by icambron** [comment]
Oops, I'm mistaken; that won't quite work. You need to set the format in Timestack explicitly:

``` js
$("#timeline").timestack({
  intervalFormat: {
     hour: "HH:mm"
   },
   dateFormat: {
      hour: "HH:mm"
   }
});
```

You can look at the "Customizing Timestack" section of the docs to set other format strings.

**Comment by air101** [comment]
Hello,

thank you. I've figuered it out eventually. But that doesn't change the locale display of weekdays/months. E.g. March to März (German). I could edit moment.js and change the default parameters but that aint a nice way :)

**Comment by icambron** [comment]
For changing March to März you need to take my first suggestion. You may also want to override Timestack's other dateFormat suboptions.
