### ISSUE TITLE
Hello cann't we use slider with this cool timeline plugin 

### ISSUE THREAD

**Issue by keshav1990** [icambron/timestack#5]
http://prntscr.com/ezi3bg

Like have problem with this

**Comment by icambron** [comment]
Not sure how I can help? It looks like there might be conflicting styles? You'll have to give me something I can reproduce.

**Comment by icambron** [comment]
Closing for now

**Comment by keshav1990** [comment]
Like you have timeline for specific time with static cannt we make it scrollable till week end
